
* When a runtime error occurs, a new `Error` object will be created and thrown. We can use `try/catch` block to handle errors ourselves rather than
  let the browsers handle it
